version: 2
updates:
  - package-ecosystem: "npm"  # Or "terraform" if checking Terraform dependencies
    directory: "/"  # Adjust if your package.json is inside a subfolder
    schedule:
      interval: "daily"  # Or "weekly"
    open-pull-requests-limit: 10
